@startuml
class com.example.demo4.models.Household {
}
class com.example.demo4.models.HouseholdChange {
}
class com.example.demo4.models.TemporaryRecord {
}
abstract class com.example.demo4.controllers.BaseController {
}
class com.example.demo4.controllers.AddHomelessCitizenController {
}
class com.example.demo4.dao.UserDao {
}
class com.example.demo4.controllers.AdminController {
}
class com.example.demo4.controllers.AdminController$UserRow {
}
class com.example.demo4.controllers.HouseholdAdminController {
}
class com.example.demo4.controllers.ReturnAssetController {
}
class com.example.demo4.dto.UserRowData {
}
class com.example.demo4.models.Citizen {
}
class com.example.demo4.controllers.AddCitizenController {
}
class com.example.demo4.controllers.UpdateEventController {
}
class com.example.demo4.dao.AssetDao {
}
class com.example.demo4.dao.CitizenChangeDao {
}
class com.example.demo4.dao.CitizenDao {
}
class com.example.demo4.EventStatusUtil {
}
class com.example.demo4.Session {
}
class com.example.demo4.models.Event {
}
class com.example.demo4.dao.BookingDao {
}
class com.example.demo4.Main {
}
class com.example.demo4.controllers.EditHouseholdController {
}
class com.example.demo4.controllers.AssignAccountController {
}
class com.example.demo4.untils.WindowUtils {
}
class com.example.demo4.controllers.AssetsController {
}
class com.example.demo4.dao.StatisticsDao {
}
class com.example.demo4.models.assets {
}
class com.example.demo4.dao.HouseholdDao {
}
class com.example.demo4.controllers.SplitHouseholdController {
}
class com.example.demo4.models.BookingAsset {
}
class com.example.demo4.controllers.HouseholdCustomerController {
}
class com.example.demo4.controllers.CustomerController {
}
class com.example.demo4.controllers.CustomerController$EventRow {
}
class com.example.demo4.controllers.EventApprovalController {
}
class com.example.demo4.controllers.EventApprovalController$EventRow {
}
class com.example.demo4.controllers.LoginController {
}
class com.example.demo4.controllers.AccountProfileController {
}
class com.example.demo4.models.Booking {
}
class com.example.demo4.controllers.EditCitizenController {
}
class com.example.demo4.controllers.RegisterController {
}
class com.example.demo4.controllers.PastEventsController {
}
class com.example.demo4.controllers.PastEventsController$EventRow {
}
class com.example.demo4.controllers.MenuController {
}
abstract class com.example.demo4.dao.BaseDao {
}
class com.example.demo4.controllers.CitizenController {
}
class com.example.demo4.controllers.ManageHouseholdMembersController {
}
class com.example.demo4.dao.TemporaryRecordDao {
}
class com.example.demo4.controllers.AddHouseholdController {
}
class com.example.demo4.dao.BookingAssetDao {
}
class com.example.demo4.Database {
}
class com.example.demo4.models.CitizenChange {
}
class com.example.demo4.controllers.AddTemporaryRecordController {
}
class com.example.demo4.controllers.WelcomeController {
}
class com.example.demo4.controllers.RentAssetController {
}
class com.example.demo4.controllers.AddEventController {
}
class com.example.demo4.models.User {
}
class com.example.demo4.dao.HouseholdChangeDao {
}
class com.example.demo4.dao.EventDao {
}
class com.example.demo4.controllers.StatisticsController {
}
class com.example.demo4.controllers.CitizenHistoryController {
}
class com.example.demo4.controllers.TemporaryRecordController {
}
class com.example.demo4.controllers.HomelessCitizenController {
}


com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AddHomelessCitizenController
com.example.demo4.dao.BaseDao <|-- com.example.demo4.dao.UserDao
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AdminController
com.example.demo4.controllers.AdminController +.. com.example.demo4.controllers.AdminController$UserRow
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.HouseholdAdminController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.ReturnAssetController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AddCitizenController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.UpdateEventController
javafx.application.Application <|-- com.example.demo4.Main
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.EditHouseholdController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AssetsController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.SplitHouseholdController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.HouseholdCustomerController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.CustomerController
com.example.demo4.controllers.CustomerController +.. com.example.demo4.controllers.CustomerController$EventRow
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.EventApprovalController
com.example.demo4.controllers.EventApprovalController +.. com.example.demo4.controllers.EventApprovalController$EventRow
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AccountProfileController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.EditCitizenController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.RegisterController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.PastEventsController
com.example.demo4.controllers.PastEventsController +.. com.example.demo4.controllers.PastEventsController$EventRow
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.MenuController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.CitizenController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.ManageHouseholdMembersController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AddHouseholdController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AddTemporaryRecordController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.RentAssetController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.AddEventController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.StatisticsController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.CitizenHistoryController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.TemporaryRecordController
com.example.demo4.controllers.BaseController <|-- com.example.demo4.controllers.HomelessCitizenController
@enduml